CREATE TABLE capture_methods (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  created_at TIMESTAMPTZ DEFAULT (now()),
  updated_at TIMESTAMPTZ DEFAULT (now()),
  deleted_at TIMESTAMPTZ,
  modified_by UUID REFERENCES auth.users (id) ON DELETE SET NULL,
  value TEXT NOT NULL,
  description TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true
);

COMMENT ON TABLE capture_methods IS 'Lookup table defining methods for capturing data (e.g., motion detection, time lapse).';

ALTER TABLE capture_methods ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for authenticated users" ON "public"."capture_methods"
AS PERMISSIVE FOR SELECT
TO authenticated
USING (true);
