
CREATE TABLE capture_methods (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  created_at timestamptz DEFAULT (now()),
  updated_at timestamptz DEFAULT (now()),
  deleted_at timestamptz,
  modified_by uuid NOT NULL REFERENCES auth.users(id),
  value text NOT NULL,
  description text NOT NULL,
  is_active boolean NOT NULL DEFAULT true
);

comment on table capture_methods is 'Lookup table defining methods for capturing data (e.g., motion detection, time lapse).';

ALTER TABLE capture_methods ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for authenticated users" ON "public"."capture_methods"
AS PERMISSIVE FOR SELECT
TO authenticated
USING (true);
