CREATE TABLE deployment_statuses (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  created_at TIMESTAMPTZ DEFAULT (now()),
  updated_at TIMESTAMPTZ DEFAULT (now()),
  deleted_at TIMESTAMPTZ,
  modified_by UUID REFERENCES auth.users (id) ON DELETE SET NULL,
  value TEXT NOT NULL,
  description TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true
);


COMMENT ON TABLE deployment_statuses IS 'Lookup table for deployment lifecycle states (e.g., planned, active, completed).';

ALTER TABLE deployment_statuses ENABLE ROW LEVEL SECURITY;
