CREATE TABLE deployment_statuses (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  created_at timestamptz DEFAULT (now()),
  updated_at timestamptz DEFAULT (now()),
  deleted_at timestamptz,
  modified_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  value text NOT NULL,
  description text NOT NULL,
  is_active boolean NOT NULL DEFAULT true
);


comment on table deployment_statuses is 'Lookup table for deployment lifecycle states (e.g., planned, active, completed).';

ALTER TABLE deployment_statuses ENABLE ROW LEVEL SECURITY;
