CREATE TABLE log_levels (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  created_at timestamptz DEFAULT (now()),
  updated_at timestamptz DEFAULT (now()),
  deleted_at timestamptz,
  value text  NOT NULL,
  description text  NOT NULL
);


comment on table log_levels is 'Lookup table defining the severity of log messages (e.g., info, error, critical).';
ALTER TABLE log_levels ENABLE ROW LEVEL SECURITY;
