CREATE TABLE log_levels (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  created_at TIMESTAMPTZ DEFAULT (now()),
  updated_at TIMESTAMPTZ DEFAULT (now()),
  deleted_at TIMESTAMPTZ,
  value TEXT NOT NULL,
  description TEXT NOT NULL
);


COMMENT ON TABLE log_levels IS 'Lookup table defining the severity of log messages (e.g., info, error, critical).';
ALTER TABLE log_levels ENABLE ROW LEVEL SECURITY;
