-- AI Model Families table for managing parent concepts of models
CREATE TABLE IF NOT EXISTS public.ai_model_families (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    firmware_model_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    organisation_id UUID NOT NULL REFERENCES public.organisations (id),
    created_by UUID REFERENCES auth.users (id),
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT uq_firmware_model_id UNIQUE (firmware_model_id),
    CONSTRAINT uq_family_per_org UNIQUE (organisation_id, name)
);

COMMENT ON TABLE public.ai_model_families IS 'Parent container for a model concept (e.g. "Rat Detection"). Each family owns a globally unique firmware_model_id used by the device.';
COMMENT ON COLUMN public.ai_model_families.firmware_model_id IS 'Globally unique integer used in firmware OP 14 and 8.3 filenames (e.g. 42V2.TFL). Decoupled from the UUID PK so database migrations never break the firmware contract.';
COMMENT ON COLUMN public.ai_model_families.organisation_id IS 'The organisation that owns this model family. Two orgs can have a model named "Rat Detection" — each gets a distinct firmware_model_id.';

CREATE INDEX IF NOT EXISTS idx_ai_model_families_org ON public.ai_model_families (organisation_id) WHERE deleted_at IS NULL;

ALTER TABLE public.ai_model_families ENABLE ROW LEVEL SECURITY;

CREATE POLICY ai_model_families_select ON public.ai_model_families
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.user_roles AS ur
            WHERE ur.user_id = auth.uid()
              AND ur.scope_type = 'organisation'
              AND ur.scope_id = ai_model_families.organisation_id
              AND ur.is_active = TRUE
              AND ur.deleted_at IS NULL
        )
    );

CREATE POLICY ai_model_families_insert ON public.ai_model_families
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.user_roles AS ur
            WHERE ur.user_id = auth.uid()
              AND ur.scope_type = 'organisation'
              AND ur.scope_id = ai_model_families.organisation_id
              AND ur.role = 'organisation_manager'
              AND ur.is_active = TRUE
              AND ur.deleted_at IS NULL
        )
    );

CREATE POLICY ai_model_families_update ON public.ai_model_families
    FOR UPDATE USING (
        EXISTS (
            SELECT 1 FROM public.user_roles AS ur
            WHERE ur.user_id = auth.uid()
              AND ur.scope_type = 'organisation'
              AND ur.scope_id = ai_model_families.organisation_id
              AND ur.role = 'organisation_manager'
              AND ur.is_active = TRUE
              AND ur.deleted_at IS NULL
        )
    );

CREATE POLICY ai_model_families_delete ON public.ai_model_families
    FOR DELETE USING (
        EXISTS (
            SELECT 1 FROM public.user_roles AS ur
            WHERE ur.user_id = auth.uid()
              AND ur.scope_type = 'organisation'
              AND ur.scope_id = ai_model_families.organisation_id
              AND ur.role = 'organisation_manager'
              AND ur.is_active = TRUE
              AND ur.deleted_at IS NULL
        )
    );

GRANT SELECT, INSERT, UPDATE, DELETE ON public.ai_model_families TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ai_model_families TO service_role;
