-- *** AI Model Families ***
--
-- Parent container for a model concept (e.g. "Rat Detection").
-- Each family owns a globally unique firmware_model_id used by the device.

CREATE TABLE ai_model_families (
  -- Internal identity (UUID for DB portability)
  id uuid PRIMARY KEY NOT NULL DEFAULT (gen_random_uuid()),

  -- Firmware identity (globally unique integer, decoupled from PK)
  firmware_model_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,

  -- Ownership
  organisation_id uuid NOT NULL REFERENCES organisations (id),
  created_by uuid REFERENCES auth.users (id),

  -- Metadata
  name text NOT NULL,
  description text,

  -- Timestamps
  created_at timestamptz DEFAULT (now()),
  updated_at timestamptz DEFAULT (now()),
  deleted_at timestamptz,

  -- Constraints
  CONSTRAINT uq_firmware_model_id UNIQUE (firmware_model_id),
  CONSTRAINT uq_family_per_org UNIQUE (organisation_id, name)
);

COMMENT ON TABLE ai_model_families IS
    'Parent container for a model concept (e.g. "Rat Detection"). '
    'Each family owns a globally unique firmware_model_id used by the device.';

COMMENT ON COLUMN ai_model_families.firmware_model_id IS
    'Globally unique integer used in firmware OP 14 and 8.3 filenames (e.g. 42V2.TFL). '
    'Decoupled from the UUID PK so database migrations never break the firmware contract.';

COMMENT ON COLUMN ai_model_families.organisation_id IS
    'The organisation that owns this model family. '
    'Two orgs can have a model named "Rat Detection" — each gets a distinct firmware_model_id.';
