-- Sampling design lookup table for wildlife capture methods
CREATE TABLE sampling_designs (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  created_at TIMESTAMPTZ DEFAULT (now()),
  updated_at TIMESTAMPTZ DEFAULT (now()),
  deleted_at TIMESTAMPTZ,
  modified_by UUID REFERENCES auth.users (id) ON DELETE SET NULL,
  value TEXT NOT NULL,
  description TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true
);

COMMENT ON TABLE sampling_designs IS 'Lookup table for wildlife sampling design methods (simpleRandom, systematicRandom, clusteredRandom, experimental, targeted, opportunistic)';
COMMENT ON COLUMN sampling_designs.value IS 'Sampling design code: simpleRandom | systematicRandom | clusteredRandom | experimental | targeted | opportunistic';
COMMENT ON COLUMN sampling_designs.description IS 'Human-readable description of the sampling design';
COMMENT ON COLUMN sampling_designs.is_active IS 'Whether this sampling design is currently available for selection';
COMMENT ON COLUMN sampling_designs.modified_by IS 'User who last modified this record';
COMMENT ON COLUMN sampling_designs.deleted_at IS 'Soft delete timestamp - NULL means active';

ALTER TABLE sampling_designs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for authenticated users" ON "public"."sampling_designs"
AS PERMISSIVE FOR SELECT
TO authenticated
USING (true);
