-- Activity detection sensitivity lookup table
CREATE TABLE activity_sensitivity (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  created_at TIMESTAMPTZ DEFAULT (now()),
  updated_at TIMESTAMPTZ DEFAULT (now()),
  deleted_at TIMESTAMPTZ,
  modified_by UUID REFERENCES auth.users (id) ON DELETE SET NULL,
  value TEXT NOT NULL,
  description TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true
);

COMMENT ON TABLE activity_sensitivity IS 'Lookup table for wildlife activity detection sensitivity levels (only for activity detection capture method)';
COMMENT ON COLUMN activity_sensitivity.value IS 'Sensitivity level: low | medium | high (only for activity detection)';
COMMENT ON COLUMN activity_sensitivity.description IS 'Human-readable description of the sensitivity level';
COMMENT ON COLUMN activity_sensitivity.is_active IS 'Whether this sensitivity level is currently available for selection';
COMMENT ON COLUMN activity_sensitivity.modified_by IS 'User who last modified this record';
COMMENT ON COLUMN activity_sensitivity.deleted_at IS 'Soft delete timestamp - NULL means active';

ALTER TABLE activity_sensitivity ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for authenticated users" ON "public"."activity_sensitivity"
AS PERMISSIVE FOR SELECT
TO authenticated
USING (true);
