CREATE TABLE api_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  deleted_at timestamptz,

  -- Core identification
  api_endpoint text,
  user_id uuid,
  project_id uuid,
  organisation_id uuid NOT NULL, -- CRITICAL: Enables org-scoped RLS
  device_id uuid,
  deployment_id uuid,

  -- Log metadata
  log_level_id int,
  log_message text,
  log_category text, -- error/warn/info/debug

  -- Tracing and context (T-002 enhancement)
  correlation_id uuid, -- Distributed tracing across requests
  session_id uuid,     -- User session tracking
  source text,         -- mobile-app/edge-function/api/webhook

  -- Application context (T-002 enhancement)
  app_version text,    -- Mobile app version (e.g., "1.2.3")
  platform text,       -- ios/android/web
  context jsonb,       -- Flexible metadata storage (user_agent, device_info, etc.)
  stack_trace text,    -- Error stack traces

  -- Foreign key constraints
  CONSTRAINT api_logs_organisation_id_fkey
    FOREIGN KEY (organisation_id) REFERENCES organisations (id) ON DELETE CASCADE,
  CONSTRAINT api_logs_project_id_fkey
    FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE SET NULL,
  CONSTRAINT api_logs_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE SET NULL
);

-- Table and column comments
COMMENT ON TABLE api_logs IS 'Captures comprehensive application logs with distributed tracing, session tracking, and flexible context storage. Supports org-scoped RLS for multi-tenant isolation.';
COMMENT ON COLUMN api_logs.api_endpoint IS 'API route or path that triggered the log entry.';
COMMENT ON COLUMN api_logs.log_level_id IS 'Level of log severity (e.g., info, error).';
COMMENT ON COLUMN api_logs.correlation_id IS 'UUID for distributed tracing across multiple requests/services.';
COMMENT ON COLUMN api_logs.session_id IS 'User session identifier for tracking user journey.';
COMMENT ON COLUMN api_logs.source IS 'Origin of the log entry (mobile-app, edge-function, api, webhook).';
COMMENT ON COLUMN api_logs.context IS 'Flexible JSONB storage for request metadata (user_agent, device_info, headers, etc.).';
COMMENT ON COLUMN api_logs.stack_trace IS 'Full error stack trace for debugging (truncate to 2KB for performance).';
COMMENT ON COLUMN api_logs.organisation_id IS 'Organisation owning this log entry. CRITICAL for RLS org-scoped access control.';
ALTER TABLE api_logs ENABLE ROW LEVEL SECURITY;
