-- Enable RLS
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE deployments ENABLE ROW LEVEL SECURITY;
ALTER TABLE devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE api_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- MVP2: Enable RLS on new tables
ALTER TABLE organisations ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_model_organisation ENABLE ROW LEVEL SECURITY;
ALTER TABLE lorawan_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE lorawan_parsed_messages ENABLE ROW LEVEL SECURITY;

-- Lookup tables
ALTER TABLE deployment_statuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE capture_methods ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_sensitivity ENABLE ROW LEVEL SECURITY;
ALTER TABLE sampling_designs ENABLE ROW LEVEL SECURITY;
ALTER TABLE log_levels ENABLE ROW LEVEL SECURITY;

-- AI model families (org-scoped isolation)
ALTER TABLE ai_model_families ENABLE ROW LEVEL SECURITY;

-- Roadmap V2: CamtrapDP and pipeline tables
ALTER TABLE media ENABLE ROW LEVEL SECURITY;
ALTER TABLE observations ENABLE ROW LEVEL SECURITY;
ALTER TABLE observation_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE taxa ENABLE ROW LEVEL SECURITY;
ALTER TABLE deployment_effort ENABLE ROW LEVEL SECURITY;
ALTER TABLE species_event_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE annotation_runs ENABLE ROW LEVEL SECURITY;

-- Grant access to authenticated users (RLS policies will filter rows)
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO service_role;

