-- *** conservation_alerts RLS Policies ***
-- Access scoped via project membership. Alerts are generated by the backend with the
-- service role; project admins may acknowledge them (UPDATE).

CREATE POLICY "Project members can view conservation_alerts"
  ON conservation_alerts
  FOR SELECT
  TO authenticated
  USING (
    has_project_role((SELECT auth.uid()), conservation_alerts.project_id, 'project_viewer')
  );

CREATE POLICY "Project admins can acknowledge conservation_alerts"
  ON conservation_alerts
  FOR UPDATE
  TO authenticated
  USING (
    has_project_role((SELECT auth.uid()), conservation_alerts.project_id, 'project_admin')
  )
  WITH CHECK (
    has_project_role((SELECT auth.uid()), conservation_alerts.project_id, 'project_admin')
  );
