-- *** Write grants the authenticated role does not get ***
-- Supabase's default privileges grant SELECT, INSERT, UPDATE and DELETE on every new
-- table to authenticated. On a table with RLS and no matching policy that grant is a
-- lie: the privilege system says yes, RLS matches no row, and the caller gets 42501 on
-- INSERT, or 0 rows and no error on UPDATE and DELETE (#178, #189). So a table that
-- clients must not write holds no write grant, and the schema says so here, in one
-- place. Test 25 fails if a table grants INSERT, UPDATE or DELETE with no policy
-- behind it.
--
-- `db:change` (CLI 2.117) generates the table-level REVOKEs below, but not column
-- grants: the notifications read_at GRANT had to be appended to its migration by
-- hand (MIGRATIONS.md section 3). Check column privileges after any change here.
--
-- Writers were traced across ww-website, ww-mobile-app and this repo for #189
-- (2026-09-30). service_role and SECURITY DEFINER functions are unaffected.

-- Written only by the ww-website backend's service role client.
REVOKE INSERT, UPDATE, DELETE ON public.api_jobs FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.cluster_assignments FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.ecological_shift_reports FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.embedding_runs FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.inat_observation_media FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.inat_observations FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.media_assets FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.media_embeddings FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.media_evidence FROM authenticated;
-- Reference data: seeds, plus the backend adding taxa with the service role.
REVOKE INSERT, UPDATE, DELETE ON public.taxa FROM authenticated;
-- No writer anywhere today; readers keep their SELECT policy.
REVOKE INSERT, UPDATE, DELETE ON public.api_logs FROM authenticated;

-- OAuth tokens, read and written only by the backend's service role. No client reads
-- them either, so SELECT goes too.
REVOKE ALL ON public.inat_tokens FROM authenticated;
-- Organisation API key hashes, the same: only the website backend's service role (#289).
REVOKE ALL ON public.api_keys FROM authenticated;

-- Profiles are written only by the handle_new_user and sync_user_email triggers.
REVOKE INSERT, UPDATE, DELETE ON public.users FROM authenticated;

-- Roles and invitations change only through the SECURITY DEFINER RPCs (invitations,
-- add/update/remove_project_member). A direct UPDATE or DELETE used to succeed with
-- 0 rows, so a client could report a removal that never happened; it now raises 42501.
REVOKE INSERT, UPDATE, DELETE ON public.user_roles FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.project_invitations FROM authenticated;

-- The backend creates notifications; recipients only mark them read. Revoking UPDATE
-- on the table also drops its column grants, so read_at is granted back.
REVOKE INSERT, UPDATE, DELETE ON public.notifications FROM authenticated;
GRANT UPDATE (read_at) ON public.notifications TO authenticated;

-- Generated by the backend; project admins may acknowledge them (UPDATE policy).
REVOKE INSERT, DELETE ON public.conservation_alerts FROM authenticated;

-- Written only by move_deployment (SECURITY DEFINER, #260). sync_deleted_ids trusts
-- these rows, so the person who moved a deployment must not be able to write one.
REVOKE INSERT, UPDATE, DELETE ON public.deployment_moves FROM authenticated;

-- DELETE (#222). These soft-delete through deleted_at (push_changes and the website
-- set it), or have no client writer at all (annotation_runs, deployment_effort, the
-- two lookups). A client DELETE used to match 0 rows with no error; it now raises
-- 42501. observations keeps DELETE: members remove wrong labels (71_observations.sql).
REVOKE DELETE ON public.annotation_runs FROM authenticated;
REVOKE DELETE ON public.capture_methods FROM authenticated;
REVOKE DELETE ON public.deployment_effort FROM authenticated;
REVOKE DELETE ON public.deployment_statuses FROM authenticated;
REVOKE DELETE ON public.deployments FROM authenticated;
REVOKE DELETE ON public.devices FROM authenticated;
REVOKE DELETE ON public.media FROM authenticated;
REVOKE DELETE ON public.observation_events FROM authenticated;
REVOKE DELETE ON public.projects FROM authenticated;
