/**
 * Supabase Client Environment Switching Tests
 *
 * Tests the factory pattern implementation for dynamic Supabase client
 * initialization and recreation when environments change.
 *
 * Coverage:
 * - Client initialization with environment config
 * - Client getter with validation
 * - Client recreation and cleanup
 * - Event emission on client changes
 * - Error handling (no environment, invalid config)
 * - Backward compatibility
 */

// Service methods to be loaded dynamically
let initializeSupabaseClient: any
let getSupabaseClient: any
let reconnectSupabase: any
let onSupabaseClientChange: any
let getCurrentEnvironment: any
let resetSupabaseClient: any
import {
	getEnvironmentConfig,
} from "../../config/EnvironmentManager"

// Mock dependencies
jest.unmock("../supabase")
jest.unmock("../../services/supabase")
jest.mock("@react-native-async-storage/async-storage")
jest.mock("@supabase/supabase-js", () => ({
	createClient: jest.fn((url, key) => ({
		_url: url,
		_key: key,
		auth: {
			getSession: jest.fn(),
			onAuthStateChange: jest.fn(() => ({
				data: { subscription: { unsubscribe: jest.fn() } },
			})),
		},
		removeAllChannels: jest.fn().mockResolvedValue([]),
		removeAllSubscriptions: jest.fn().mockResolvedValue([]),
		from: jest.fn(),
		_isTestClient: true,
	})),
}))
jest.mock("../../config/EnvironmentManager")

// Don't mock the entire supabase module, just the EnvironmentManager it depends on
// This allows us to test the actual implementation

// Import createClient after mocking
import { createClient } from "@supabase/supabase-js"

describe("Supabase Client Environment Switching", () => {
	let mockCreateClient: jest.MockedFunction<typeof createClient>
	let mockGetEnvironmentConfig: jest.MockedFunction<typeof getEnvironmentConfig>

	beforeEach(() => {
        jest.resetModules() // Ensure we get fresh modules with our local mocks
        
        // Capture fresh mocks generated by the factory re-evaluation
        mockCreateClient = require("@supabase/supabase-js").createClient
        mockGetEnvironmentConfig = require("../../config/EnvironmentManager").getEnvironmentConfig

		jest.clearAllMocks()

        // Restore our specific mock implementation because sanitySetup.ts overwrites it in its beforeEach
        mockCreateClient.mockImplementation((url, key) => ({
            _url: url,
            _key: key,
            auth: {
                getSession: jest.fn(),
                onAuthStateChange: jest.fn(() => ({
                    data: { subscription: { unsubscribe: jest.fn() } },
                })),
            },
            removeAllChannels: jest.fn().mockResolvedValue([]),
            removeAllSubscriptions: jest.fn().mockResolvedValue([]),
            from: jest.fn(),
            _isTestClient: true,
        }) as any)

        // Dynamically load the service module to ensure valid unmocked instance
        const supabaseModule = require("../supabase")
        initializeSupabaseClient = supabaseModule.initializeSupabaseClient
        getSupabaseClient = supabaseModule.getSupabaseClient
        reconnectSupabase = supabaseModule.reconnectSupabase
        onSupabaseClientChange = supabaseModule.onSupabaseClientChange
        getCurrentEnvironment = supabaseModule.getCurrentEnvironment
        resetSupabaseClient = supabaseModule.resetSupabaseClient

		// Default mock: cloud-dev environment
		mockGetEnvironmentConfig.mockResolvedValue({
			supabaseUrl: "https://test.supabase.co",
			supabaseAnonKey: "test-anon-key",
			websiteUrl: "https://wildlifewatcher.ai",
			displayName: "Test Environment",
			description: "Test description",
			isProduction: false,
		})

		// Reset client state
		resetSupabaseClient()
	})

	describe("initializeSupabaseClient", () => {
		it("should initialize client with current environment config", async () => {
			const client = await initializeSupabaseClient()

			expect(mockGetEnvironmentConfig).toHaveBeenCalledTimes(1)
			expect(mockCreateClient).toHaveBeenCalledWith(
				"https://test.supabase.co",
				"test-anon-key",
				expect.objectContaining({
					auth: expect.objectContaining({
						storage: expect.anything(), // AsyncStorage is passed but object comparison fails
						autoRefreshToken: true,
						persistSession: true,
						detectSessionInUrl: false,
					}),
				}),
			)
			expect(client).toBeDefined()
			expect((client as any)._isTestClient).toBe(true)
		})

		it("should store client instance for later retrieval", async () => {
			const client1 = await initializeSupabaseClient()
			const client2 = getSupabaseClient()

			expect(client1).toBe(client2)
		})

		it("should replace existing client when called multiple times", async () => {
			const client1 = await initializeSupabaseClient()
			const client2 = await initializeSupabaseClient()

			expect(client1).not.toBe(client2)
			expect(mockCreateClient).toHaveBeenCalledTimes(2)
		})

		it("should handle environment config retrieval errors", async () => {
			mockGetEnvironmentConfig.mockRejectedValueOnce(
				new Error("Config error"),
			)

			await expect(initializeSupabaseClient()).rejects.toThrow("Config error")
		})

		it("should use custom auth options when provided", async () => {
			await initializeSupabaseClient({
				auth: {
					autoRefreshToken: false,
					persistSession: false,
				},
			})

			expect(mockCreateClient).toHaveBeenCalledWith(
				"https://test.supabase.co",
				"test-anon-key",
				expect.objectContaining({
					auth: expect.objectContaining({
						autoRefreshToken: false,
						persistSession: false,
					}),
				}),
			)
		})
	})

	describe("getSupabaseClient", () => {
		it("should throw error if client not initialized", () => {
			expect(() => getSupabaseClient()).toThrow(
				"Supabase client not initialized",
			)
		})

		it("should return initialized client", async () => {
			await initializeSupabaseClient()
			const client = getSupabaseClient()

			expect(client).toBeDefined()
			expect((client as any)._isTestClient).toBe(true)
		})

		it("should return same instance on multiple calls", async () => {
			await initializeSupabaseClient()
			const client1 = getSupabaseClient()
			const client2 = getSupabaseClient()

			expect(client1).toBe(client2)
		})
	})

	describe("reconnectSupabase", () => {
		it("should cleanup old client before creating new one", async () => {
			const client1 = await initializeSupabaseClient()
			// Check for removeAllChannels as that's the modern API
			const mockRemoveChannels = (client1 as any).removeAllChannels as jest.Mock

			await reconnectSupabase()

			expect(mockRemoveChannels).toHaveBeenCalledTimes(1)
		})

		it("should create new client with current environment", async () => {
			await initializeSupabaseClient()

			// Change environment
			mockGetEnvironmentConfig.mockResolvedValueOnce({
				supabaseUrl: "https://new.supabase.co",
				supabaseAnonKey: "new-anon-key",
				websiteUrl: "https://wildlifewatcher.ai",
				displayName: "New Environment",
				description: "New description",
				isProduction: false,
			})

			await reconnectSupabase()

			expect(mockCreateClient).toHaveBeenCalledWith(
				"https://new.supabase.co",
				"new-anon-key",
				expect.any(Object),
			)
		})

		it("should emit client-changed event after reconnection", async () => {
			await initializeSupabaseClient()

			const mockCallback = jest.fn()
			onSupabaseClientChange(mockCallback)

			await reconnectSupabase()

			expect(mockCallback).toHaveBeenCalledTimes(1)
		})

		it("should handle errors during cleanup gracefully", async () => {
			const client1 = await initializeSupabaseClient()
			const mockRemoveChannels = (client1 as any).removeAllChannels as jest.Mock
			mockRemoveChannels.mockRejectedValueOnce(new Error("Cleanup error"))

			// Should not throw, but should log error
			const consoleErrorSpy = jest
				.spyOn(console, "error")
				.mockImplementation(() => { })

			await reconnectSupabase()

			expect(consoleErrorSpy).toHaveBeenCalledWith(
				"⚠️ Error cleaning up old Supabase client:",
				expect.any(Error),
			)

			consoleErrorSpy.mockRestore()
		})

		it("should create client even if no previous client exists", async () => {
			const client = await reconnectSupabase()

			expect(client).toBeDefined()
			expect(mockCreateClient).toHaveBeenCalledTimes(1)
		})
	})

	describe("onSupabaseClientChange", () => {
		it("should register callback for client changes", async () => {
			await initializeSupabaseClient()

			const mockCallback = jest.fn()
			const unsubscribe = onSupabaseClientChange(mockCallback)

			await reconnectSupabase()

			expect(mockCallback).toHaveBeenCalledTimes(1)
			expect(typeof unsubscribe).toBe("function")
		})

		it("should unsubscribe callback when unsubscribe function is called", async () => {
			await initializeSupabaseClient()

			const mockCallback = jest.fn()
			const unsubscribe = onSupabaseClientChange(mockCallback)

			unsubscribe()

			await reconnectSupabase()

			expect(mockCallback).not.toHaveBeenCalled()
		})

		it("should support multiple subscribers", async () => {
			await initializeSupabaseClient()

			const callback1 = jest.fn()
			const callback2 = jest.fn()

			onSupabaseClientChange(callback1)
			onSupabaseClientChange(callback2)

			await reconnectSupabase()

			expect(callback1).toHaveBeenCalledTimes(1)
			expect(callback2).toHaveBeenCalledTimes(1)
		})

		it("should handle callback errors gracefully", async () => {
			await initializeSupabaseClient()

			const errorCallback = jest.fn(() => {
				throw new Error("Callback error")
			})
			const validCallback = jest.fn()

			onSupabaseClientChange(validCallback)
			onSupabaseClientChange(errorCallback)

			const consoleErrorSpy = jest
				.spyOn(console, "error")
				.mockImplementation(() => { })

			await reconnectSupabase()

			expect(errorCallback).toHaveBeenCalledTimes(1)
			expect(validCallback).toHaveBeenCalledTimes(1)
			expect(consoleErrorSpy).toHaveBeenCalled()

			consoleErrorSpy.mockRestore()
		})
	})

	describe("getCurrentEnvironment", () => {
		it("should return current environment from last initialization", async () => {
			mockGetEnvironmentConfig.mockResolvedValueOnce({
				supabaseUrl: "https://test.supabase.co",
				supabaseAnonKey: "test-key",
				websiteUrl: "https://wildlifewatcher.ai",
				displayName: "Test Env",
				description: "Test",
				isProduction: false,
			})

			await initializeSupabaseClient()
			const env = getCurrentEnvironment()

			expect(env).toEqual({
				supabaseUrl: "https://test.supabase.co",
				supabaseAnonKey: "test-key",
				websiteUrl: "https://wildlifewatcher.ai",
				displayName: "Test Env",
				description: "Test",
				isProduction: false,
			})
		})

		it("should return null if client not initialized", () => {
			const env = getCurrentEnvironment()
			expect(env).toBeNull()
		})

		it("should update after reconnection", async () => {
			await initializeSupabaseClient()

			mockGetEnvironmentConfig.mockResolvedValueOnce({
				supabaseUrl: "https://new.supabase.co",
				supabaseAnonKey: "new-key",
				websiteUrl: "https://wildlifewatcher.ai",
				displayName: "New Env",
				description: "New",
				isProduction: true,
			})

			await reconnectSupabase()
			const env = getCurrentEnvironment()

			expect(env?.supabaseUrl).toBe("https://new.supabase.co")
			expect(env?.isProduction).toBe(true)
		})
	})

	describe("Integration: Full environment switch workflow", () => {
		it("should handle complete environment switch from local to cloud-dev", async () => {
			// Step 1: Initialize with local environment
			mockGetEnvironmentConfig.mockResolvedValueOnce({
				supabaseUrl: "http://localhost:54321",
				supabaseAnonKey: "local-key",
				websiteUrl: "http://localhost:5173",
				displayName: "Local",
				description: "Local Supabase",
				isProduction: false,
			})

			const client1 = await initializeSupabaseClient()
			expect((client1 as any)._url).toBe("http://localhost:54321")

			// Step 2: Change environment
			mockGetEnvironmentConfig.mockResolvedValueOnce({
				supabaseUrl: "https://cloud.supabase.co",
				supabaseAnonKey: "cloud-key",
				websiteUrl: "https://wildlifewatcher.ai",
				displayName: "Cloud Dev",
				description: "Cloud Development",
				isProduction: false,
			})

			// Step 3: Reconnect
			const callback = jest.fn()
			onSupabaseClientChange(callback)

			const client2 = await reconnectSupabase()

			// Verify cleanup and recreation
			expect((client1 as any).removeAllChannels).toHaveBeenCalled()
			expect((client2 as any)._url).toBe("https://cloud.supabase.co")
			expect(callback).toHaveBeenCalled()

			// Step 4: Verify new client is active
			const activeClient = getSupabaseClient()
			expect(activeClient).toBe(client2)
		})
	})

	describe("Backward compatibility", () => {
		it("should maintain supabase export for legacy code", async () => {
			// This test verifies the deprecated export still works
			// In actual implementation, this will log a warning
			const { supabase } = require("../supabase")

			expect(supabase).toBeDefined()
			// Legacy export should return function that gets current client
		})
	})

	describe("Error scenarios", () => {
		it("should handle missing environment config gracefully", async () => {
			mockGetEnvironmentConfig.mockResolvedValueOnce({
				supabaseUrl: "",
				supabaseAnonKey: "",
				websiteUrl: "https://wildlifewatcher.ai",
				displayName: "Invalid",
				description: "Invalid config",
				isProduction: false,
			})

			await expect(initializeSupabaseClient()).rejects.toThrow()
		})

		it("should handle createClient failures", async () => {
			mockCreateClient.mockImplementationOnce(() => {
				throw new Error("Client creation failed")
			})

			await expect(initializeSupabaseClient()).rejects.toThrow(
				"Client creation failed",
			)
		})
	})

	describe("Memory management", () => {
		it("should not leak event listeners on multiple reconnects", async () => {
			await initializeSupabaseClient()

			const callback = jest.fn()
			const unsubscribe = onSupabaseClientChange(callback)

			// Multiple reconnects
			await reconnectSupabase()
			await reconnectSupabase()
			await reconnectSupabase()

			// Should be called 3 times (once per reconnect)
			expect(callback).toHaveBeenCalledTimes(3)

			// Cleanup
			unsubscribe()

			await reconnectSupabase()

			// Should still be 3 (not called after unsubscribe)
			expect(callback).toHaveBeenCalledTimes(3)
		})

		it("should cleanup subscriptions on each reconnect", async () => {
			const client1 = await initializeSupabaseClient()
			await reconnectSupabase()
			const client2 = getSupabaseClient()
			await reconnectSupabase()

			expect((client1 as any).removeAllChannels).toHaveBeenCalledTimes(1)
			expect((client2 as any).removeAllChannels).toHaveBeenCalledTimes(1)
		})
	})
})
