/**
 * ⚠️ WARNING: DO NOT MANUALLY EDIT THIS FILE ⚠️
 * 
 * This file is AUTOMATICALLY GENERATED by `npm run schema:generate`.
 * Manual modifications will be lost.
 * 
 * Sources:
 * - src/types/database.types.ts (Supabase Schema)
 * - scripts/generate-watermelon-schema.js (Generator Logic)
 */

import { appSchema, tableSchema } from '@nozbe/watermelondb'

export default appSchema({
    version: 254,
    tables: [
        tableSchema({
            name: 'project_invitations',
            columns: [
                { name: 'remote_id', type: 'string', isIndexed: true },
                { name: 'project_id', type: 'string', isIndexed: true },
                { name: 'inviter_id', type: 'string' },
                { name: 'invitee_email', type: 'string' },
                { name: 'invitee_id', type: 'string', isOptional: true },
                { name: 'role', type: 'string' },
                { name: 'status', type: 'string' },
                { name: 'expires_at', type: 'number' },
                { name: 'responded_at', type: 'number', isOptional: true },
                // System & Sync Fields
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
                { name: 'deleted_at', type: 'number' },
                { name: '_version', type: 'number' },
                { name: '_custom_sync_status', type: 'string', isOptional: true },
                { name: 'modified_by', type: 'string' },
            ],
        }),
        tableSchema({
            name: 'sync_outbox',
            columns: [
                { name: 'operation_id', type: 'string', isIndexed: true },
                { name: 'operation_type', type: 'string' },
                { name: 'table_name', type: 'string', isIndexed: true },
                { name: 'record_id', type: 'string', isIndexed: true },
                { name: 'payload', type: 'string' },
                { name: 'version', type: 'number' },
                { name: 'lamport_clock', type: 'number' },
                { name: 'retry_count', type: 'number' },
                { name: 'status', type: 'string', isIndexed: true },
                { name: 'error_message', type: 'string', isOptional: true },
                { name: 'user_id', type: 'string', isOptional: true },
                { name: 'device_id', type: 'string', isOptional: true },
                // System & Sync Fields
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
                { name: 'deleted_at', type: 'number' },
                { name: '_version', type: 'number' },
                { name: '_custom_sync_status', type: 'string', isOptional: true },
                { name: 'modified_by', type: 'string' },
            ],
        }),
        tableSchema({
            name: 'sync_state',
            columns: [
                { name: 'key', type: 'string', isIndexed: true },
                { name: 'value', type: 'string' },
                { name: 'updated_at', type: 'number' },
            ],
        }),
    ],
})
