/**
 * File transfer types, error codes, and observability structures.
 *
 * Matches the protocol defined in app_developer_spec.md and
 * the nRF52 implementation in fileTx.c / fileTx.h.
 */

// ─── Packet type bytes (BLE packet byte 0) ───────────────────────────
export const FILE_START    = 7
export const FILE_DATA     = 8
export const FILE_END      = 9
export const FILE_LOOPBACK = 10

// ─── Limits ──────────────────────────────────────────────────────────
/** Hard application limit. Real files: firmware ~2MB, models ~1-5MB. */
export const MAX_TRANSFER_SIZE_BYTES = 10 * 1024 * 1024 // 10 MB

/** Maximum payload bytes per FILE_DATA packet (244 MTU - 3 header). */
export const MAX_PAYLOAD_BYTES = 241

// ─── Timeouts ────────────────────────────────────────────────────────
/** Time to wait for a specific ACK response. */
export const ACK_TIMEOUT_MS = 10_000

/** Time with zero ftx-prefixed UART activity before declaring device stuck. */
export const SILENCE_TIMEOUT_MS = 15_000

/** Max consecutive ACK timeouts before auto-abort (Bluetooth unstable). */
export const MAX_CONSECUTIVE_TIMEOUTS = 3

// ─── nRF52 Error Codes (1-4) ─────────────────────────────────────────
// HX6538 Error Codes (5-10) — forwarded unchanged by nRF52
export enum FileTxErrorCode {
  WRONG_STATE       = 1, // Packet arrived outside expected transfer state
  MALFORMED         = 2, // Packet too short or payload length invalid
  BAD_FILENAME      = 3, // Filename failed 8.3 format validation
  I2C_FAIL          = 4, // I2C send to HX6538 failed
  // 5+ are generated by the HX6538 and forwarded unchanged
  HX_BAD_FILENAME   = 5, // Filename validation failed on AI processor
  FILE_OPEN_FAIL    = 6, // Failed to open or create file on SD card
  SD_WRITE_FAIL     = 7, // SD card write failed
  SEQUENCE_ERROR    = 8, // Packet number mismatch (out-of-order)
  CRC_MISMATCH      = 9, // Whole-file CRC mismatch at end of transfer
  MALFORMED_FRAME   = 10, // Malformed frame (e.g. zero-length chunk)
}

// ─── Retry policy per error code ─────────────────────────────────────
export type RetryPolicy = 'auto_once' | 'never' | 'operator' | 'manual_intervention'

export const ERROR_RETRY_POLICY: Record<number, RetryPolicy> = {
  [FileTxErrorCode.WRONG_STATE]:      'auto_once',
  [FileTxErrorCode.MALFORMED]:        'never',
  [FileTxErrorCode.BAD_FILENAME]:     'never',
  [FileTxErrorCode.I2C_FAIL]:         'operator',
  [FileTxErrorCode.HX_BAD_FILENAME]:  'never',
  [FileTxErrorCode.FILE_OPEN_FAIL]:   'operator',
  [FileTxErrorCode.SD_WRITE_FAIL]:    'operator',
  [FileTxErrorCode.SEQUENCE_ERROR]:   'never',
  [FileTxErrorCode.CRC_MISMATCH]:     'auto_once',
  [FileTxErrorCode.MALFORMED_FRAME]:  'never',
}

export function getRetryPolicy(code: number): RetryPolicy {
  return ERROR_RETRY_POLICY[code] ?? 'manual_intervention'
}

// ─── User-friendly error messages ────────────────────────────────────
export const ERROR_MESSAGES: Record<number, string> = {
  [FileTxErrorCode.WRONG_STATE]:      'Device was not ready for this packet. Try again.',
  [FileTxErrorCode.MALFORMED]:        'Internal error: malformed packet. Please report this issue.',
  [FileTxErrorCode.BAD_FILENAME]:     'Invalid filename. Use 8.3 format with uppercase letters and digits.',
  [FileTxErrorCode.I2C_FAIL]:         'Communication with AI processor failed. Try again.',
  [FileTxErrorCode.HX_BAD_FILENAME]:  'AI processor rejected the filename. Use 8.3 format (e.g. OUTPUT.IMG).',
  [FileTxErrorCode.FILE_OPEN_FAIL]:   'Failed to open or create file on SD card. Check the SD card.',
  [FileTxErrorCode.SD_WRITE_FAIL]:    'SD card write failed. Check the SD card and try again.',
  [FileTxErrorCode.SEQUENCE_ERROR]:   'Packet arrived out of order. Transfer aborted.',
  [FileTxErrorCode.CRC_MISMATCH]:     'File corrupted during transfer (CRC mismatch). Try again.',
  [FileTxErrorCode.MALFORMED_FRAME]:  'Device received a malformed frame. Please report this issue.',
}

export function getErrorMessage(code: number): string {
  return ERROR_MESSAGES[code] ?? `SD card error (code ${code}). Check the SD card and try again.`
}

// ─── Transfer progress ──────────────────────────────────────────────
export interface FileTransferProgress {
  phase: 'checking' | 'preparing' | 'starting' | 'transferring' | 'verifying' | 'complete' | 'failed'
  bytesSent: number
  totalBytes: number
  currentPacket: number    // monotonic, not wire number
  totalPackets: number
  percentage: number       // 0-100
  elapsedMs: number
  estimatedRemainingMs: number
  currentSpeed: string     // e.g. "1.2 KB/s"
}

// ─── Transfer result ─────────────────────────────────────────────────
export interface FileTransferResult {
  success: boolean
  filename: string
  sizeBytes: number
  durationMs: number
  totalPackets: number
  crc: number
  errorCode?: number
  errorMessage?: string
}

// ─── Transfer error ──────────────────────────────────────────────────
export type FileTransferFailureReason =
  | 'DEVICE_ERROR'       // ftx err <N>
  | 'ACK_TIMEOUT'        // expected ACK not received
  | 'DEVICE_SILENT'      // no ftx UART activity
  | 'DISCONNECTED'       // BLE connection lost
  | 'ABORTED'            // user cancelled
  | 'WRITE_FAILED'       // BLE write rejected by OS
  | 'VALIDATION_FAILED'  // pre-flight check failed

export class FileTransferError extends Error {
  constructor(
    public readonly reason: FileTransferFailureReason,
    message: string,
    public readonly errorCode?: number,
  ) {
    super(message)
    this.name = 'FileTransferError'
  }
}

// ─── Observability log ───────────────────────────────────────────────
export interface FileTransferLog {
  transferId: string
  deviceId: string
  filename: string
  sizeBytes: number
  crc: number
  maxPayloadBytes: number
  totalPackets: number

  // Timing
  startTime: string        // ISO 8601
  endTime: string
  durationMs: number

  // Progress
  packetsAcked: number
  lastAckedPacket: number   // wire number
  wrapCycles: number

  // Outcome
  finalStatus: FileTransferFailureReason | 'success'
  errorCode?: number
  errorMessage?: string
  disconnectOccurred: boolean
  crcVerified: boolean      // true only if "ftx done" received

  // Environment
  platform: string
  appVersion: string
}

// ─── Pipeline options ────────────────────────────────────────────────
export interface FileTransferOptions {
  filename: string
  data: Uint8Array
  onProgress?: (progress: FileTransferProgress) => void
  abortSignal?: AbortSignal
  /**
   * Window size for pipelining (packets in flight). Defaults to 12.
   * Firmware >= 0.30.47 acks only every 4th data packet, so values <= 4
   * (including 1 = stop-and-wait) deadlock against it - override only for
   * protocol testing against known firmware.
   */
  windowSize?: number
}
